# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 00:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BorschApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 11, 27, 3, 37, 14, 224544)),
        ),
    ]
