# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'DealWithMeal' do
  use_frameworks!
  pod 'Alamofire', '~> 3.4'
  pod 'SwiftyJSON'
  pod 'MWPhotoBrowser', '~> 2.1'
  pod 'SideMenu'
  pod 'NVActivityIndicatorView'
  pod 'SDWebImage', '~>3.8'
  pod 'CardIO'
  pod 'DZNEmptyDataSet'
  pod 'ReachabilitySwift'
  pod 'PeekView'
  pod 'XLForm', :git => 'https://github.com/xmartlabs/XLForm.git'
  pod 'Fashion'
  pod 'SlideMenuControllerSwift'
  pod 'GoogleMaps'
end
